import React from "react";
import Sdata from "./Sdata";
import Card from "./Cards";

const Netflix = () => {
  return (
    <>
      <Card
        key={Sdata[0].id}
        imgsrc={Sdata[0].imgsrc}
        title={Sdata[0].title}
        sname={Sdata[0].sname}
        link={Sdata[0].link}
      />
      <Card
        key={Sdata[1].id}
        imgsrc={Sdata[1].imgsrc}
        title={Sdata[1].title}
        sname={Sdata[1].sname}
        link={Sdata[1].link}
      />
      <Card
        key={Sdata[2].id}
        imgsrc={Sdata[2].imgsrc}
        title={Sdata[2].title}
        sname={Sdata[2].sname}
        link={Sdata[2].link}
      />
      <Card
        key={Sdata[3].id}
        imgsrc={Sdata[3].imgsrc}
        title={Sdata[3].title}
        sname={Sdata[3].sname}
        link={Sdata[3].link}
      />
      <Card
        key={Sdata[4].id}
        imgsrc={Sdata[4].imgsrc}
        title={Sdata[4].title}
        sname={Sdata[4].sname}
        link={Sdata[4].link}
      />
      <Card
        key={Sdata[5].id}
        imgsrc={Sdata[5].imgsrc}
        title={Sdata[5].title}
        sname={Sdata[5].sname}
        link={Sdata[5].link}
      />
      <Card
        key={Sdata[6].id}
        imgsrc={Sdata[6].imgsrc}
        title={Sdata[6].title}
        sname={Sdata[6].sname}
        link={Sdata[6].link}
      />
      <Card
        key={Sdata[7].id}
        imgsrc={Sdata[7].imgsrc}
        title={Sdata[7].title}
        sname={Sdata[7].sname}
        link={Sdata[7].link}
      />
      <Card
        key={Sdata[8].id}
        imgsrc={Sdata[8].imgsrc}
        title={Sdata[8].title}
        sname={Sdata[8].sname}
        link={Sdata[8].link}
      />
      <Card
        key={Sdata[9].id}
        imgsrc={Sdata[9].imgsrc}
        title={Sdata[9].title}
        sname={Sdata[9].sname}
        link={Sdata[9].link}
      />
      <Card
        key={Sdata[10].id}
        imgsrc={Sdata[10].imgsrc}
        title={Sdata[10].title}
        sname={Sdata[10].sname}
        link={Sdata[10].link}
      />
      <Card
        key={Sdata[11].id}
        imgsrc={Sdata[11].imgsrc}
        title={Sdata[11].title}
        sname={Sdata[11].sname}
        link={Sdata[11].link}
      />
    </>
  );
};

export default Netflix;
